using System.Collections.Generic;
using System.Linq;
using System.Text;
using Majipro.Converter.Abstrations;
using Majipro.Converter.Generator.Conversions;
using Majipro.Converter.Generator.Extensions;
using Majipro.Converter.Generator.Rules;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace Majipro.Converter.Generator.Generating;

/// <summary>
/// Writes the converter for one pair, or nothing when no rule knows how. The class around the body
/// is decided by what writing the body turned out to need, not by anything asked beforehand.
/// </summary>
internal sealed class ConverterEmitter
{
    private readonly ConversionSemantics _semantics;
    private readonly ConversionQueue _queue;
    private readonly IReadOnlyList<IConverterBodyRule> _bodyRules;

    public ConverterEmitter(
        ConversionSemantics semantics,
        ConversionQueue queue,
        IReadOnlyList<IConverterBodyRule> bodyRules)
    {
        _semantics = semantics;
        _queue = queue;
        _bodyRules = bodyRules;
    }

    public IEnumerable<GeneratedSource> Emit(ConversionPair pair)
    {
        // Same type conversions are handled by ConvertingService itself, and a type the generated
        // file can not even name is not a conversion this generator can write.
        if (pair.IsIdentity || pair.From.GetUnderlyingType().IsVisibleToGeneratedCode() == false)
        {
            yield break;
        }

        var context = new ConverterContext(_semantics, _queue, pair);
        var body = _bodyRules.FirstMatch(r => r.Body(context)).FirstOrDefault();

        if (body == null)
        {
            yield break;
        }

        yield return new GeneratedSource(context.FileName, Render(context, body));
    }

    private SourceText Render(ConverterContext context, StatementSyntax body)
    {
        var sourceCode = GetCompilationUnit(context, body)
            .NormalizeWhitespace()
            .SyntaxTree
            .GetText()
            .ToString();

        return SourceText.From(sourceCode, Encoding.UTF8);
    }

    private CompilationUnitSyntax GetCompilationUnit(ConverterContext context, StatementSyntax body)
    {
        return CompilationUnit()
            .WithMembers(
                SingletonList<MemberDeclarationSyntax>(
                    NamespaceDeclaration(ParseName(ConverterSyntax.GeneratedNamespace))
                        .WithMembers(
                            SingletonList<MemberDeclarationSyntax>(
                                GetConverterClass(context, body)))))
            .WithLeadingTrivia(GetHeader());
    }

    /// <summary>
    /// <c>// &lt;auto-generated/&gt;</c> keeps the file out of code analysis, <c>#nullable disable</c>
    /// keeps <c>return default</c> quiet in projects with the nullable context turned on.
    /// </summary>
    private static SyntaxTriviaList GetHeader()
    {
        return TriviaList(
            Comment("// <auto-generated/>"),
            Trivia(
                NullableDirectiveTrivia(
                    Token(SyntaxKind.DisableKeyword),
                    true)));
    }

    private ClassDeclarationSyntax GetConverterClass(ConverterContext context, StatementSyntax body)
    {
        // The method is built first on purpose: whether the converting service is needed is known
        // only once the body has been written.
        var convert = GetConvertMethod(context, body);
        var members = new List<MemberDeclarationSyntax>();

        if (context.RequiresConvertingService)
        {
            members.Add(GetConvertingServiceField());
            members.Add(GetConstructor(context));
        }

        members.Add(convert);

        return ClassDeclaration(context.ClassName)
            .WithModifiers(
                TokenList(
                    Token(SyntaxKind.PublicKeyword),
                    Token(SyntaxKind.SealedKeyword)))
            .WithBaseList(
                BaseList(
                    SingletonSeparatedList<BaseTypeSyntax>(
                        SimpleBaseType(
                            ConverterSyntax.TypeName(_semantics.Converter(context.Pair))))))
            .WithMembers(List(members));
    }

    private static MethodDeclarationSyntax GetConvertMethod(ConverterContext context, StatementSyntax body)
    {
        var statements = new List<StatementSyntax>();

        // Value types that are not nullable are never null, their converters skip the check.
        if (context.Pair.From.CanBeNull())
        {
            statements.Add(GetNullCheck());
        }

        statements.Add(body);

        return MethodDeclaration(
                ConverterSyntax.TypeName(context.Pair.To),
                Identifier(ConverterSyntax.ConvertMethodName))
            .WithModifiers(
                TokenList(
                    Token(SyntaxKind.PublicKeyword)))
            .WithParameterList(
                ParameterList(
                    SingletonSeparatedList(
                        Parameter(ConverterSyntax.FromIdentifier())
                            .WithType(ConverterSyntax.TypeName(context.Pair.From)))))
            .WithBody(Block(statements));
    }

    private static StatementSyntax GetNullCheck()
    {
        return IfStatement(
            ConverterSyntax.IsNull(ConverterSyntax.From()),
            Block(
                SingletonList<StatementSyntax>(
                    ReturnStatement(
                        LiteralExpression(
                            SyntaxKind.DefaultLiteralExpression,
                            Token(SyntaxKind.DefaultKeyword))))));
    }

    /// <summary>
    /// Properties that need a converter of their own are converted by the converting service, which
    /// is injected the same way a hand written converter would inject it.
    /// </summary>
    private static MemberDeclarationSyntax GetConvertingServiceField()
    {
        return FieldDeclaration(
                VariableDeclaration(ConverterSyntax.TypeName(typeof(IConvertingService)))
                    .WithVariables(
                        SingletonSeparatedList(
                            VariableDeclarator(
                                Identifier(ConverterSyntax.ConvertingServiceFieldName)))))
            .WithModifiers(
                TokenList(
                    Token(SyntaxKind.PrivateKeyword),
                    Token(SyntaxKind.ReadOnlyKeyword)));
    }

    private static MemberDeclarationSyntax GetConstructor(ConverterContext context)
    {
        return ConstructorDeclaration(Identifier(context.ClassName))
            .WithModifiers(
                TokenList(
                    Token(SyntaxKind.PublicKeyword)))
            .WithParameterList(
                ParameterList(
                    SingletonSeparatedList(
                        Parameter(Identifier(ConverterSyntax.ConvertingServiceParameterName))
                            .WithType(ConverterSyntax.TypeName(typeof(IConvertingService))))))
            .WithBody(
                Block(
                    SingletonList<StatementSyntax>(
                        ExpressionStatement(
                            AssignmentExpression(
                                SyntaxKind.SimpleAssignmentExpression,
                                IdentifierName(ConverterSyntax.ConvertingServiceFieldName),
                                IdentifierName(ConverterSyntax.ConvertingServiceParameterName))))));
    }
}
