using System.Text;
using Majipro.Converter.Generator.Analysis;
using Microsoft.CodeAnalysis.Text;

namespace Majipro.Converter.Generator.Generating;

/// <summary>
/// Emits the converter as plain text. Every type is fully qualified, so the generated file
/// never needs a using directive and can not collide with anything in the target project.
/// </summary>
internal static class ConverterSourceBuilder
{
    internal const string GeneratedNamespace = "Majipro.Converter.Generated";

    internal static SourceText Build(ConversionInfo conversion)
    {
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable disable");
        builder.AppendLine();
        builder.AppendLine("namespace " + GeneratedNamespace);
        builder.AppendLine("{");
        builder.AppendLine("    public sealed class " + conversion.ClassName + " : " + conversion.ConverterInterfaceFullName);
        builder.AppendLine("    {");
        builder.AppendLine("        public " + conversion.ToFullName + " Convert(" + conversion.FromFullName + " from)");
        builder.AppendLine("        {");

        if (conversion.RequiresNullCheck)
        {
            builder.AppendLine("            if (from == null)");
            builder.AppendLine("            {");
            builder.AppendLine("                return default;");
            builder.AppendLine("            }");
            builder.AppendLine();
        }

        builder.AppendLine("            return new " + conversion.ToFullName);
        builder.AppendLine("            {");

        foreach (var property in conversion.Properties)
        {
            builder.AppendLine("                " + property.To.Name + " = from." + property.From.Name + ",");
        }

        builder.AppendLine("            };");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        return SourceText.From(builder.ToString(), Encoding.UTF8);
    }
}
