using System.Collections.Generic;
using System.Linq;
using System.Text;
using Majipro.Converter.Abstrations;
using Majipro.Converter.Generator.Conversions;
using Majipro.Converter.Generator.Extensions;
using Majipro.Converter.Generator.Rules;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace Majipro.Converter.Generator.Generating;

/// <summary>
/// Writes the converter for one pair, or nothing when no rule knows how. The class around the body
/// is decided by what writing the body turned out to need, not by anything asked beforehand - the
/// converting service it takes, and the interface it implements: a converter that turned out to be
/// able to fill a target somebody already holds is written as an <c>IReferenceConverter</c>, which
/// is two conversions in one class, because that interface extends <c>IConverter</c>.
/// </summary>
internal sealed class ConverterEmitter
{
    private readonly ConversionSemantics _semantics;
    private readonly ConversionQueue _queue;
    private readonly IReadOnlyList<IConverterBodyRule> _bodyRules;

    public ConverterEmitter(
        ConversionSemantics semantics,
        ConversionQueue queue,
        IReadOnlyList<IConverterBodyRule> bodyRules)
    {
        _semantics = semantics;
        _queue = queue;
        _bodyRules = bodyRules;
    }

    public IEnumerable<GeneratedSource> Emit(ConversionPair pair)
    {
        // Same type conversions are handled by ConvertingService itself, and a type the generated
        // file can not even name is not a conversion this generator can write.
        if (pair.IsIdentity || pair.From.GetUnderlyingType().IsVisibleToGeneratedCode() == false)
        {
            yield break;
        }

        var context = new ConverterContext(_semantics, _queue, pair);
        var body = _bodyRules.FirstMatch(r => r.Body(context)).FirstOrDefault();

        if (body == null)
        {
            yield break;
        }

        yield return new GeneratedSource(context.FileName, Render(context, body));
    }

    private SourceText Render(ConverterContext context, ConverterBody body)
    {
        var sourceCode = GetCompilationUnit(context, body)
            .NormalizeWhitespace()
            .SyntaxTree
            .GetText()
            .ToString();

        return SourceText.From(sourceCode, Encoding.UTF8);
    }

    private CompilationUnitSyntax GetCompilationUnit(ConverterContext context, ConverterBody body)
    {
        return CompilationUnit()
            .WithMembers(
                SingletonList<MemberDeclarationSyntax>(
                    NamespaceDeclaration(ParseName(ConverterSyntax.GeneratedNamespace))
                        .WithMembers(
                            SingletonList<MemberDeclarationSyntax>(
                                GetConverterClass(context, body)))))
            .WithLeadingTrivia(GetHeader());
    }

    /// <summary>
    /// <c>// &lt;auto-generated/&gt;</c> keeps the file out of code analysis, <c>#nullable disable</c>
    /// keeps <c>return default</c> quiet in projects with the nullable context turned on.
    /// </summary>
    private static SyntaxTriviaList GetHeader()
    {
        return TriviaList(
            Comment("// <auto-generated/>"),
            Trivia(
                NullableDirectiveTrivia(
                    Token(SyntaxKind.DisableKeyword),
                    true)));
    }

    private ClassDeclarationSyntax GetConverterClass(ConverterContext context, ConverterBody body)
    {
        var members = new List<MemberDeclarationSyntax>();

        if (context.RequiresConvertingService)
        {
            members.Add(GetConvertingServiceField());
            members.Add(GetConstructor(context));
        }

        members.Add(GetCreateMethod(context, body.Create));

        if (body.Fill != null)
        {
            members.Add(GetFillMethod(context, body.Fill));
        }

        return ClassDeclaration(context.ClassName)
            .WithModifiers(
                TokenList(
                    Token(SyntaxKind.PublicKeyword),
                    Token(SyntaxKind.SealedKeyword)))
            .WithBaseList(
                BaseList(
                    SingletonSeparatedList<BaseTypeSyntax>(
                        SimpleBaseType(
                            ConverterSyntax.TypeName(_semantics.Converter(context.Pair, body.Fill != null))))))
            .WithMembers(List(members));
    }

    /// <summary><c>TTo Convert(TFrom from)</c>, the conversion every generated converter has.</summary>
    private static MethodDeclarationSyntax GetCreateMethod(ConverterContext context, StatementSyntax body)
    {
        var statements = new List<StatementSyntax>();

        // Value types that are not nullable are never null, their converters skip the check.
        if (context.Pair.From.CanBeNull())
        {
            statements.Add(GetNullCheck(ConverterSyntax.Default()));
        }

        statements.Add(body);

        return GetConvertMethod(context, statements, GetFromParameter(context));
    }

    /// <summary>
    /// <c>TTo Convert(TFrom from, TTo to)</c>, the second conversion, written only for a target that
    /// can be filled after it exists. The target is returned rather than created, so what the caller
    /// gets back is the instance it passed in.
    /// </summary>
    private static MethodDeclarationSyntax GetFillMethod(
        ConverterContext context,
        IReadOnlyList<StatementSyntax> body)
    {
        var statements = new List<StatementSyntax>();

        // There is nothing to enhance the target with, so it is handed back the way it came in.
        if (context.Pair.From.CanBeNull())
        {
            statements.Add(GetNullCheck(ConverterSyntax.To()));
        }

        statements.AddRange(body);
        statements.Add(ReturnStatement(ConverterSyntax.To()));

        return GetConvertMethod(
            context,
            statements,
            GetFromParameter(context),
            Parameter(Identifier(ConverterSyntax.ToParameterName))
                .WithType(ConverterSyntax.TypeName(context.Pair.To)));
    }

    private static MethodDeclarationSyntax GetConvertMethod(
        ConverterContext context,
        IReadOnlyList<StatementSyntax> statements,
        params ParameterSyntax[] parameters)
    {
        return MethodDeclaration(
                ConverterSyntax.TypeName(context.Pair.To),
                Identifier(ConverterSyntax.ConvertMethodName))
            .WithModifiers(
                TokenList(
                    Token(SyntaxKind.PublicKeyword)))
            .WithParameterList(ParameterList(SeparatedList(parameters)))
            .WithBody(Block(statements));
    }

    private static ParameterSyntax GetFromParameter(ConverterContext context)
    {
        return Parameter(ConverterSyntax.FromIdentifier())
            .WithType(ConverterSyntax.TypeName(context.Pair.From));
    }

    private static StatementSyntax GetNullCheck(ExpressionSyntax result)
    {
        return IfStatement(
            ConverterSyntax.IsNull(ConverterSyntax.From()),
            Block(
                SingletonList<StatementSyntax>(
                    ReturnStatement(result))));
    }

    /// <summary>
    /// Properties that need a converter of their own are converted by the converting service, which
    /// is injected the same way a hand written converter would inject it.
    /// </summary>
    private static MemberDeclarationSyntax GetConvertingServiceField()
    {
        return FieldDeclaration(
                VariableDeclaration(ConverterSyntax.TypeName(typeof(IConvertingService)))
                    .WithVariables(
                        SingletonSeparatedList(
                            VariableDeclarator(
                                Identifier(ConverterSyntax.ConvertingServiceFieldName)))))
            .WithModifiers(
                TokenList(
                    Token(SyntaxKind.PrivateKeyword),
                    Token(SyntaxKind.ReadOnlyKeyword)));
    }

    private static MemberDeclarationSyntax GetConstructor(ConverterContext context)
    {
        return ConstructorDeclaration(Identifier(context.ClassName))
            .WithModifiers(
                TokenList(
                    Token(SyntaxKind.PublicKeyword)))
            .WithParameterList(
                ParameterList(
                    SingletonSeparatedList(
                        Parameter(Identifier(ConverterSyntax.ConvertingServiceParameterName))
                            .WithType(ConverterSyntax.TypeName(typeof(IConvertingService))))))
            .WithBody(
                Block(
                    SingletonList<StatementSyntax>(
                        ExpressionStatement(
                            AssignmentExpression(
                                SyntaxKind.SimpleAssignmentExpression,
                                IdentifierName(ConverterSyntax.ConvertingServiceFieldName),
                                IdentifierName(ConverterSyntax.ConvertingServiceParameterName))))));
    }
}
