using System.Collections.Generic;
using System.Linq;
using System.Text;
using Majipro.Converter.Abstrations;
using Majipro.Converter.Generator.Analysis;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace Majipro.Converter.Generator.Generating;

/// <summary>
/// Builds the converter as a syntax tree and renders it by <see cref="SyntaxNodeExtensions.NormalizeWhitespace{TNode}"/>.
/// Every type is written as a fully qualified name, so the generated file never needs a using
/// directive and can not collide with anything in the target project.
/// </summary>
internal static class ConverterSourceBuilder
{
    internal const string GeneratedNamespace = "Majipro.Converter.Generated";

    private const string ConvertMethodName = nameof(IConverter<object, object>.Convert);
    private const string FromParameterName = "from";

    internal static SourceText Build(ConversionInfo conversion)
    {
        var sourceCode = GetCompilationUnit(conversion)
            .NormalizeWhitespace()
            .SyntaxTree
            .GetText()
            .ToString();

        return SourceText.From(sourceCode, Encoding.UTF8);
    }

    private static CompilationUnitSyntax GetCompilationUnit(ConversionInfo conversion)
    {
        return CompilationUnit()
            .WithMembers(
                SingletonList<MemberDeclarationSyntax>(
                    NamespaceDeclaration(
                        ParseName(GeneratedNamespace))
                    .WithMembers(
                        SingletonList<MemberDeclarationSyntax>(
                            GetConverterClass(conversion)))))
            .WithLeadingTrivia(GetHeader());
    }

    /// <summary>
    /// <c>// &lt;auto-generated/&gt;</c> keeps the file out of code analysis, <c>#nullable disable</c>
    /// keeps <c>return default</c> quiet in projects with the nullable context turned on.
    /// </summary>
    private static SyntaxTriviaList GetHeader()
    {
        return TriviaList(
            Comment("// <auto-generated/>"),
            Trivia(
                NullableDirectiveTrivia(
                    Token(SyntaxKind.DisableKeyword),
                    true)));
    }

    private static ClassDeclarationSyntax GetConverterClass(ConversionInfo conversion)
    {
        return ClassDeclaration(conversion.ClassName)
            .WithModifiers(
                TokenList(
                    Token(SyntaxKind.PublicKeyword),
                    Token(SyntaxKind.SealedKeyword)))
            .WithBaseList(
                BaseList(
                    SingletonSeparatedList<BaseTypeSyntax>(
                        SimpleBaseType(
                            ParseTypeName(conversion.ConverterInterfaceFullName)))))
            .WithMembers(
                SingletonList<MemberDeclarationSyntax>(
                    GetConvertMethod(conversion)));
    }

    private static MethodDeclarationSyntax GetConvertMethod(ConversionInfo conversion)
    {
        var body = new List<StatementSyntax>();

        if (conversion.RequiresNullCheck)
        {
            body.Add(GetNullCheck());
        }

        body.Add(GetConversion(conversion));

        return MethodDeclaration(
                ParseTypeName(conversion.ToFullName),
                Identifier(ConvertMethodName))
            .WithModifiers(
                TokenList(
                    Token(SyntaxKind.PublicKeyword)))
            .WithParameterList(
                ParameterList(
                    SingletonSeparatedList(
                        Parameter(GetFromIdentifier())
                            .WithType(
                                ParseTypeName(conversion.FromFullName)))))
            .WithBody(
                Block(body));
    }

    private static StatementSyntax GetNullCheck()
    {
        return IfStatement(
            BinaryExpression(
                SyntaxKind.EqualsExpression,
                IdentifierName(GetFromIdentifier()),
                LiteralExpression(SyntaxKind.NullLiteralExpression)),
            Block(
                SingletonList<StatementSyntax>(
                    ReturnStatement(
                        LiteralExpression(
                            SyntaxKind.DefaultLiteralExpression,
                            Token(SyntaxKind.DefaultKeyword))))));
    }

    private static StatementSyntax GetConversion(ConversionInfo conversion)
    {
        var assignments = conversion.Properties
            .Select(GetPropertyAssignment)
            .Cast<ExpressionSyntax>();

        return ReturnStatement(
            ObjectCreationExpression(
                ParseTypeName(conversion.ToFullName))
            .WithInitializer(
                InitializerExpression(
                    SyntaxKind.ObjectInitializerExpression,
                    SeparatedList(assignments))));
    }

    private static AssignmentExpressionSyntax GetPropertyAssignment(PropertyMapping mapping)
    {
        return AssignmentExpression(
            SyntaxKind.SimpleAssignmentExpression,
            IdentifierName(mapping.To.Name),
            MemberAccessExpression(
                SyntaxKind.SimpleMemberAccessExpression,
                IdentifierName(GetFromIdentifier()),
                IdentifierName(mapping.From.Name)));
    }

    /// <summary>
    /// <c>from</c> is a contextual keyword, so it has to be created as one.
    /// </summary>
    private static SyntaxToken GetFromIdentifier()
    {
        return Identifier(
            TriviaList(),
            SyntaxKind.FromKeyword,
            FromParameterName,
            FromParameterName,
            TriviaList());
    }
}
