using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Majipro.Converter.Abstrations;
using Majipro.Converter.Generator.Analysis;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace Majipro.Converter.Generator.Generating;

/// <summary>
/// Builds the converter as a syntax tree and renders it by <see cref="SyntaxNodeExtensions.NormalizeWhitespace{TNode}"/>.
/// Every type is written as a fully qualified name, so the generated file never needs a using
/// directive and can not collide with anything in the target project.
/// </summary>
internal static class ConverterSourceBuilder
{
    internal const string GeneratedNamespace = "Majipro.Converter.Generated";

    private const string ConvertMethodName = nameof(IConverter<object, object>.Convert);
    private const string FromParameterName = "from";
    private const string ConvertingServiceParameterName = "convertingService";
    private const string ConvertingServiceFieldName = "_" + ConvertingServiceParameterName;

    internal static SourceText Build(ConversionInfo conversion)
    {
        var sourceCode = GetCompilationUnit(conversion)
            .NormalizeWhitespace()
            .SyntaxTree
            .GetText()
            .ToString();

        return SourceText.From(sourceCode, Encoding.UTF8);
    }

    private static CompilationUnitSyntax GetCompilationUnit(ConversionInfo conversion)
    {
        return CompilationUnit()
            .WithMembers(
                SingletonList<MemberDeclarationSyntax>(
                    NamespaceDeclaration(
                        ParseName(GeneratedNamespace))
                    .WithMembers(
                        SingletonList<MemberDeclarationSyntax>(
                            GetConverterClass(conversion)))))
            .WithLeadingTrivia(GetHeader());
    }

    /// <summary>
    /// <c>// &lt;auto-generated/&gt;</c> keeps the file out of code analysis, <c>#nullable disable</c>
    /// keeps <c>return default</c> quiet in projects with the nullable context turned on.
    /// </summary>
    private static SyntaxTriviaList GetHeader()
    {
        return TriviaList(
            Comment("// <auto-generated/>"),
            Trivia(
                NullableDirectiveTrivia(
                    Token(SyntaxKind.DisableKeyword),
                    true)));
    }

    private static ClassDeclarationSyntax GetConverterClass(ConversionInfo conversion)
    {
        var members = new List<MemberDeclarationSyntax>();

        if (conversion.RequiresConvertingService)
        {
            members.Add(GetConvertingServiceField());
            members.Add(GetConstructor(conversion));
        }

        members.Add(GetConvertMethod(conversion));

        return ClassDeclaration(conversion.ClassName)
            .WithModifiers(
                TokenList(
                    Token(SyntaxKind.PublicKeyword),
                    Token(SyntaxKind.SealedKeyword)))
            .WithBaseList(
                BaseList(
                    SingletonSeparatedList<BaseTypeSyntax>(
                        SimpleBaseType(
                            ParseTypeName(conversion.ConverterInterfaceFullName)))))
            .WithMembers(
                List(members));
    }

    /// <summary>
    /// Properties that need a converter of their own are converted by the converting service, which
    /// is injected the same way a hand written converter would inject it.
    /// </summary>
    private static MemberDeclarationSyntax GetConvertingServiceField()
    {
        return FieldDeclaration(
                VariableDeclaration(
                    GetGlobalTypeName(typeof(IConvertingService)))
                .WithVariables(
                    SingletonSeparatedList(
                        VariableDeclarator(
                            Identifier(ConvertingServiceFieldName)))))
            .WithModifiers(
                TokenList(
                    Token(SyntaxKind.PrivateKeyword),
                    Token(SyntaxKind.ReadOnlyKeyword)));
    }

    private static MemberDeclarationSyntax GetConstructor(ConversionInfo conversion)
    {
        return ConstructorDeclaration(
                Identifier(conversion.ClassName))
            .WithModifiers(
                TokenList(
                    Token(SyntaxKind.PublicKeyword)))
            .WithParameterList(
                ParameterList(
                    SingletonSeparatedList(
                        Parameter(
                            Identifier(ConvertingServiceParameterName))
                        .WithType(
                            GetGlobalTypeName(typeof(IConvertingService))))))
            .WithBody(
                Block(
                    SingletonList<StatementSyntax>(
                        ExpressionStatement(
                            AssignmentExpression(
                                SyntaxKind.SimpleAssignmentExpression,
                                IdentifierName(ConvertingServiceFieldName),
                                IdentifierName(ConvertingServiceParameterName))))));
    }

    private static MethodDeclarationSyntax GetConvertMethod(ConversionInfo conversion)
    {
        var body = new List<StatementSyntax>();

        if (conversion.RequiresNullCheck)
        {
            body.Add(GetNullCheck());
        }

        body.Add(conversion.IsToStringConversion
            ? GetToStringConversion()
            : GetConversion(conversion));

        return MethodDeclaration(
                ParseTypeName(conversion.ToFullName),
                Identifier(ConvertMethodName))
            .WithModifiers(
                TokenList(
                    Token(SyntaxKind.PublicKeyword)))
            .WithParameterList(
                ParameterList(
                    SingletonSeparatedList(
                        Parameter(GetFromIdentifier())
                            .WithType(
                                ParseTypeName(conversion.FromFullName)))))
            .WithBody(
                Block(body));
    }

    private static StatementSyntax GetNullCheck()
    {
        return IfStatement(
            BinaryExpression(
                SyntaxKind.EqualsExpression,
                IdentifierName(GetFromIdentifier()),
                LiteralExpression(SyntaxKind.NullLiteralExpression)),
            Block(
                SingletonList<StatementSyntax>(
                    ReturnStatement(
                        LiteralExpression(
                            SyntaxKind.DefaultLiteralExpression,
                            Token(SyntaxKind.DefaultKeyword))))));
    }

    /// <summary>
    /// <c>System.Convert.ToString</c> is what a hand written <c>anything -&gt; string</c> converter
    /// would do, and it is the only thing that can be done without knowing the source type.
    /// </summary>
    private static StatementSyntax GetToStringConversion()
    {
        return ReturnStatement(
            InvocationExpression(
                MemberAccessExpression(
                    SyntaxKind.SimpleMemberAccessExpression,
                    GetGlobalTypeName(typeof(System.Convert)),
                    IdentifierName(nameof(System.Convert.ToString))))
            .WithArgumentList(
                ArgumentList(
                    SingletonSeparatedList(
                        Argument(
                            IdentifierName(GetFromIdentifier()))))));
    }

    private static StatementSyntax GetConversion(ConversionInfo conversion)
    {
        var assignments = conversion.Properties
            .Select(p => GetPropertyAssignment(conversion, p))
            .Cast<ExpressionSyntax>();

        return ReturnStatement(
            ObjectCreationExpression(
                ParseTypeName(conversion.ToValueFullName))
            .WithInitializer(
                InitializerExpression(
                    SyntaxKind.ObjectInitializerExpression,
                    SeparatedList(assignments))));
    }

    private static AssignmentExpressionSyntax GetPropertyAssignment(ConversionInfo conversion, PropertyMapping mapping)
    {
        return AssignmentExpression(
            SyntaxKind.SimpleAssignmentExpression,
            IdentifierName(mapping.To.Name),
            GetPropertyValue(conversion, mapping));
    }

    private static ExpressionSyntax GetPropertyValue(ConversionInfo conversion, PropertyMapping mapping)
    {
        var source = GetSourceProperty(conversion, mapping);

        switch (mapping.Kind)
        {
            case PropertyMappingKind.Converted:
                return GetConvertCall(mapping.ConvertedFromFullName, mapping.ConvertedToFullName, source);

            case PropertyMappingKind.Collection:
                return GetCollectionValue(mapping, source);

            default:
                return source;
        }
    }

    /// <summary>
    /// <c>from.Property</c>, or <c>from.Value.Property</c> when the converter takes a nullable structure.
    /// </summary>
    private static ExpressionSyntax GetSourceProperty(ConversionInfo conversion, PropertyMapping mapping)
    {
        ExpressionSyntax source = IdentifierName(GetFromIdentifier());

        if (conversion.SourceIsNullableValueType)
        {
            source = MemberAccessExpression(
                SyntaxKind.SimpleMemberAccessExpression,
                source,
                IdentifierName(nameof(Nullable<int>.Value)));
        }

        return MemberAccessExpression(
            SyntaxKind.SimpleMemberAccessExpression,
            source,
            IdentifierName(mapping.From.Name));
    }

    /// <summary>
    /// A collection is converted item by item by the converting service and materialized into a
    /// <see cref="List{T}"/>, which fits every collection interface the target property can be.
    /// </summary>
    private static ExpressionSyntax GetCollectionValue(PropertyMapping mapping, ExpressionSyntax source)
    {
        var items = GetConvertCall(
            mapping.ConvertedFromFullName,
            mapping.ConvertedToFullName,
            CastExpression(
                GetGlobalTypeName(typeof(IEnumerable<>), mapping.ConvertedFromFullName),
                source));

        ExpressionSyntax value = ObjectCreationExpression(
                GetGlobalTypeName(typeof(List<>), mapping.ConvertedToFullName))
            .WithArgumentList(
                ArgumentList(
                    SingletonSeparatedList(
                        Argument(items))));

        if (mapping.SourceCanBeNull == false)
        {
            return value;
        }

        return ConditionalExpression(
            BinaryExpression(
                SyntaxKind.EqualsExpression,
                source,
                LiteralExpression(SyntaxKind.NullLiteralExpression)),
            LiteralExpression(SyntaxKind.NullLiteralExpression),
            value);
    }

    private static ExpressionSyntax GetConvertCall(string fromFullName, string toFullName, ExpressionSyntax argument)
    {
        return InvocationExpression(
                MemberAccessExpression(
                    SyntaxKind.SimpleMemberAccessExpression,
                    IdentifierName(ConvertingServiceFieldName),
                    GenericName(
                        Identifier(ConvertMethodName))
                    .WithTypeArgumentList(
                        TypeArgumentList(
                            SeparatedList(
                                new[]
                                {
                                    ParseTypeName(fromFullName),
                                    ParseTypeName(toFullName)
                                })))))
            .WithArgumentList(
                ArgumentList(
                    SingletonSeparatedList(
                        Argument(argument))));
    }

    /// <summary>
    /// Writes a framework type the generated code needs as a fully qualified name taken from the
    /// type itself, so there is no name written by hand.
    /// </summary>
    private static TypeSyntax GetGlobalTypeName(Type type, string? typeArgumentFullName = null)
    {
        var name = type.FullName ?? type.Name;
        var arity = name.IndexOf('`');

        if (arity >= 0)
        {
            name = name.Substring(0, arity);
        }

        name = "global::" + name;

        return ParseTypeName(typeArgumentFullName == null
            ? name
            : name + "<" + typeArgumentFullName + ">");
    }

    /// <summary>
    /// <c>from</c> is a contextual keyword, so it has to be created as one.
    /// </summary>
    private static SyntaxToken GetFromIdentifier()
    {
        return Identifier(
            TriviaList(),
            SyntaxKind.FromKeyword,
            FromParameterName,
            FromParameterName,
            TriviaList());
    }
}
